# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'writeflowfilemainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadNodeTablePushButton = QtWidgets.QPushButton(self.groupBox)
        self.loadNodeTablePushButton.setObjectName("loadNodeTablePushButton")
        self.horizontalLayout.addWidget(self.loadNodeTablePushButton)
        self.nodeTableLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nodeTableLineEdit.setEnabled(True)
        self.nodeTableLineEdit.setReadOnly(True)
        self.nodeTableLineEdit.setObjectName("nodeTableLineEdit")
        self.horizontalLayout.addWidget(self.nodeTableLineEdit)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.specOutputGroupBox = QtWidgets.QGroupBox(self.frame)
        self.specOutputGroupBox.setEnabled(True)
        self.specOutputGroupBox.setObjectName("specOutputGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.specOutputGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.addSpecOutputPushButton = QtWidgets.QPushButton(self.specOutputGroupBox)
        self.addSpecOutputPushButton.setEnabled(False)
        self.addSpecOutputPushButton.setObjectName("addSpecOutputPushButton")
        self.gridLayout.addWidget(self.addSpecOutputPushButton, 0, 0, 1, 1)
        self.specOutputListWidget = QtWidgets.QListWidget(self.specOutputGroupBox)
        self.specOutputListWidget.setEnabled(False)
        self.specOutputListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.specOutputListWidget.setObjectName("specOutputListWidget")
        self.gridLayout.addWidget(self.specOutputListWidget, 0, 1, 4, 1)
        self.clearSpecOutputPushButton = QtWidgets.QPushButton(self.specOutputGroupBox)
        self.clearSpecOutputPushButton.setEnabled(False)
        self.clearSpecOutputPushButton.setObjectName("clearSpecOutputPushButton")
        self.gridLayout.addWidget(self.clearSpecOutputPushButton, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.specOutputGroupBox)
        self.horizontalLayout_2.addWidget(self.frame)
        self.flowFileGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.flowFileGroupBox.setEnabled(False)
        self.flowFileGroupBox.setObjectName("flowFileGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.flowFileGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox1 = QtWidgets.QGroupBox(self.flowFileGroupBox)
        self.groupBox1.setObjectName("groupBox1")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox1)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.startDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox1)
        self.startDateTimeEdit.setCalendarPopup(True)
        self.startDateTimeEdit.setObjectName("startDateTimeEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startDateTimeEdit)
        self.label_2 = QtWidgets.QLabel(self.groupBox1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.endDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox1)
        self.endDateTimeEdit.setCalendarPopup(True)
        self.endDateTimeEdit.setObjectName("endDateTimeEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.endDateTimeEdit)
        self.label_3 = QtWidgets.QLabel(self.groupBox1)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.timeStepComboBox = QtWidgets.QComboBox(self.groupBox1)
        self.timeStepComboBox.setObjectName("timeStepComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.timeStepComboBox)
        self.verticalLayout.addWidget(self.groupBox1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.saveFlowFilePushButton = QtWidgets.QPushButton(self.flowFileGroupBox)
        self.saveFlowFilePushButton.setObjectName("saveFlowFilePushButton")
        self.verticalLayout.addWidget(self.saveFlowFilePushButton)
        self.horizontalLayout_2.addWidget(self.flowFileGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.startDateTimeEdit)
        self.label_2.setBuddy(self.endDateTimeEdit)
        self.label_3.setBuddy(self.timeStepComboBox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Node Table"))
        self.loadNodeTablePushButton.setText(_translate("MainWindow", "&Load"))
        self.specOutputGroupBox.setTitle(_translate("MainWindow", "Special Output Files"))
        self.addSpecOutputPushButton.setText(_translate("MainWindow", "&Add"))
        self.clearSpecOutputPushButton.setText(_translate("MainWindow", "&Clear"))
        self.flowFileGroupBox.setTitle(_translate("MainWindow", "Flow File"))
        self.groupBox1.setTitle(_translate("MainWindow", "Time Series"))
        self.label.setText(_translate("MainWindow", "&Start"))
        self.startDateTimeEdit.setDisplayFormat(_translate("MainWindow", "M/d/yyyy hh:mm"))
        self.label_2.setText(_translate("MainWindow", "&End"))
        self.endDateTimeEdit.setDisplayFormat(_translate("MainWindow", "M/d/yyyy hh:mm"))
        self.label_3.setText(_translate("MainWindow", "&Time Step"))
        self.saveFlowFilePushButton.setText(_translate("MainWindow", "&Save Flow File"))

