# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'writeflowfilemainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 291)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupbox = QtWidgets.QGroupBox(self.frame)
        self.groupbox.setObjectName("groupbox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupbox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadNodeTablePushButton = QtWidgets.QPushButton(self.groupbox)
        self.loadNodeTablePushButton.setObjectName("loadNodeTablePushButton")
        self.horizontalLayout.addWidget(self.loadNodeTablePushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.groupbox)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addWidget(self.groupbox)
        self.groupbox1 = QtWidgets.QGroupBox(self.frame)
        self.groupbox1.setObjectName("groupbox1")
        self.gridLayout = QtWidgets.QGridLayout(self.groupbox1)
        self.gridLayout.setObjectName("gridLayout")
        self.clearSpecOutputPushButton = QtWidgets.QPushButton(self.groupbox1)
        self.clearSpecOutputPushButton.setObjectName("clearSpecOutputPushButton")
        self.gridLayout.addWidget(self.clearSpecOutputPushButton, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.addSpecOutputPushButton = QtWidgets.QPushButton(self.groupbox1)
        self.addSpecOutputPushButton.setObjectName("addSpecOutputPushButton")
        self.gridLayout.addWidget(self.addSpecOutputPushButton, 0, 0, 1, 1)
        self.specOutputFileBrowser = QtWidgets.QTextBrowser(self.groupbox1)
        self.specOutputFileBrowser.setObjectName("specOutputFileBrowser")
        self.gridLayout.addWidget(self.specOutputFileBrowser, 0, 1, 4, 1)
        self.verticalLayout_2.addWidget(self.groupbox1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.flowFileGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.flowFileGroupBox.setEnabled(False)
        self.flowFileGroupBox.setObjectName("flowFileGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.flowFileGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupbox2 = QtWidgets.QGroupBox(self.flowFileGroupBox)
        self.groupbox2.setObjectName("groupbox2")
        self.formLayout = QtWidgets.QFormLayout(self.groupbox2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupbox2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.startDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupbox2)
        self.startDateTimeEdit.setCalendarPopup(True)
        self.startDateTimeEdit.setObjectName("startDateTimeEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startDateTimeEdit)
        self.label_2 = QtWidgets.QLabel(self.groupbox2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.endDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupbox2)
        self.endDateTimeEdit.setCalendarPopup(True)
        self.endDateTimeEdit.setObjectName("endDateTimeEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.endDateTimeEdit)
        self.label_3 = QtWidgets.QLabel(self.groupbox2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.timeStepComboBox = QtWidgets.QComboBox(self.groupbox2)
        self.timeStepComboBox.setObjectName("timeStepComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.timeStepComboBox)
        self.verticalLayout.addWidget(self.groupbox2)
        self.groupbox3 = QtWidgets.QGroupBox(self.flowFileGroupBox)
        self.groupbox3.setObjectName("groupbox3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupbox3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupbox3)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupbox3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupbox3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.saveFlowFilePushButton = QtWidgets.QPushButton(self.flowFileGroupBox)
        self.saveFlowFilePushButton.setObjectName("saveFlowFilePushButton")
        self.verticalLayout.addWidget(self.saveFlowFilePushButton)
        self.horizontalLayout_2.addWidget(self.flowFileGroupBox)
        self.loadNodeTablePushButton.raise_()
        self.lineEdit.raise_()
        self.lineEdit.raise_()
        self.specOutputFileBrowser.raise_()
        self.addSpecOutputPushButton.raise_()
        self.clearSpecOutputPushButton.raise_()
        self.specOutputFileBrowser.raise_()
        self.pushButton.raise_()
        self.lineEdit_2.raise_()
        self.saveFlowFilePushButton.raise_()
        self.startDateTimeEdit.raise_()
        self.timeStepComboBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.endDateTimeEdit.raise_()
        self.label_3.raise_()
        self.saveFlowFilePushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupbox.setTitle(_translate("MainWindow", "Node Table"))
        self.loadNodeTablePushButton.setText(_translate("MainWindow", "&Load"))
        self.groupbox1.setTitle(_translate("MainWindow", "Special Output Files"))
        self.clearSpecOutputPushButton.setText(_translate("MainWindow", "&Clear"))
        self.addSpecOutputPushButton.setText(_translate("MainWindow", "&Add"))
        self.flowFileGroupBox.setTitle(_translate("MainWindow", "Flow File"))
        self.groupbox2.setTitle(_translate("MainWindow", "Time Series"))
        self.label.setText(_translate("MainWindow", "&Start"))
        self.startDateTimeEdit.setDisplayFormat(_translate("MainWindow", "M/d/yyyy hh:mm"))
        self.label_2.setText(_translate("MainWindow", "&End"))
        self.endDateTimeEdit.setDisplayFormat(_translate("MainWindow", "M/d/yyyy hh:mm"))
        self.label_3.setText(_translate("MainWindow", "&Time Step"))
        self.groupbox3.setTitle(_translate("MainWindow", "Output Location"))
        self.pushButton.setText(_translate("MainWindow", "Select "))
        self.saveFlowFilePushButton.setText(_translate("MainWindow", "&Save Flow File"))

